/**
 * 分镜脚本 PDF 导出 — 客户端生成
 *
 * 使用 jspdf 在浏览器端生成 PDF，避免服务端中文字体问题。
 * 结构：封面页 + 内容页（每页 2 个场景并排）
 */

import { jsPDF } from 'jspdf';
import type { Script } from './types';
import { SCENE_TYPE_LABELS } from '@/data/template.schema';

// PDF 常量
const PAGE_WIDTH = 297; // A4 横版宽 mm
const PAGE_HEIGHT = 210; // A4 横版高 mm
const MARGIN = 15;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

/**
 * 将图片 URL 转换为 Base64 data URL
 * 跨域图片通过 canvas 转换
 */
async function imageUrlToBase64(url: string): Promise<string | null> {
    try {
        const response = await fetch(url, { mode: 'cors' });
        const blob = await response.blob();
        return new Promise((resolve) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(reader.result as string);
            reader.onerror = () => resolve(null);
            reader.readAsDataURL(blob);
        });
    } catch {
        // 如果 fetch 失败，尝试 canvas 方式
        try {
            return await new Promise((resolve) => {
                const img = new Image();
                img.crossOrigin = 'anonymous';
                img.onload = () => {
                    const canvas = document.createElement('canvas');
                    canvas.width = img.naturalWidth;
                    canvas.height = img.naturalHeight;
                    const ctx = canvas.getContext('2d');
                    ctx?.drawImage(img, 0, 0);
                    resolve(canvas.toDataURL('image/jpeg', 0.8));
                };
                img.onerror = () => resolve(null);
                img.src = url;
            });
        } catch {
            return null;
        }
    }
}

/**
 * 导出分镜脚本为 PDF
 */
export async function exportStoryboardPDF(script: Script): Promise<void> {
    // 横版 A4 (landscape)
    const doc = new jsPDF({
        orientation: 'landscape',
        unit: 'mm',
        format: 'a4',
    });

    // jsPDF 默认不支持中文字体，我们用 doc.html 不了
    // 使用基本绘图 + 内嵌标准字体
    // 注意：jsPDF 标准字体不支持 CJK 字符，需要 fallback 方案

    // ===== 封面页 =====
    drawCoverPage(doc, script);

    // ===== 预加载所有图片 =====
    const imageCache = new Map<string, string>();
    for (const scene of script.scenes) {
        if (scene.imageUrl) {
            const base64 = await imageUrlToBase64(scene.imageUrl);
            if (base64) {
                imageCache.set(scene.id, base64);
            }
        }
    }

    // ===== 内容页：每页 2 个场景 =====
    const scenes = script.scenes;
    for (let i = 0; i < scenes.length; i += 2) {
        doc.addPage();

        // 左场景
        drawSceneBlock(doc, scenes[i], i, MARGIN, MARGIN, CONTENT_WIDTH / 2 - 5, imageCache);

        // 右场景（如果存在）
        if (i + 1 < scenes.length) {
            drawSceneBlock(doc, scenes[i + 1], i + 1, MARGIN + CONTENT_WIDTH / 2 + 5, MARGIN, CONTENT_WIDTH / 2 - 5, imageCache);
        }

        // 页脚
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(
            `${script.title} — ${Math.floor(i / 2) + 1}/${Math.ceil(scenes.length / 2)}`,
            PAGE_WIDTH / 2,
            PAGE_HEIGHT - 5,
            { align: 'center' },
        );
    }

    // ===== 保存 =====
    const filename = `${script.title.replace(/[^\w\u4e00-\u9fa5-]/g, '_')}_分镜脚本.pdf`;
    doc.save(filename);
}

function drawCoverPage(doc: jsPDF, script: Script) {
    // 背景渐变效果（简化为纯色块）
    doc.setFillColor(124, 58, 237); // #7C3AED 主色
    doc.rect(0, 0, PAGE_WIDTH, 80, 'F');

    // 标题
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    // jsPDF 标准字体不支持中文，用英文标注 + 场景数
    doc.text('Storyboard Script', PAGE_WIDTH / 2, 35, { align: 'center' });

    doc.setFontSize(12);
    doc.text(script.title, PAGE_WIDTH / 2, 50, { align: 'center' });

    // 信息区
    doc.setTextColor(80, 80, 80);
    doc.setFontSize(11);
    const infoY = 100;

    doc.text(`Scenes: ${script.scenes.length}`, MARGIN + 20, infoY);
    doc.text(`Total Duration: ${script.totalDuration}s`, MARGIN + 20, infoY + 10);
    doc.text(`Mode: ${script.generationMode === 'template' ? 'Template-driven' : 'Free creation'}`, MARGIN + 20, infoY + 20);
    doc.text(`Date: ${new Date().toLocaleDateString('zh-CN')}`, MARGIN + 20, infoY + 30);

    if (script.templateId) {
        doc.text(`Template ID: ${script.templateId.substring(0, 8)}...`, MARGIN + 20, infoY + 40);
    }

    // 底部 branding
    doc.setFontSize(9);
    doc.setTextColor(180, 180, 180);
    doc.text('Generated by Viral Workshop (baokuangongfang.com)', PAGE_WIDTH / 2, PAGE_HEIGHT - 10, { align: 'center' });
}

function drawSceneBlock(
    doc: jsPDF,
    scene: Script['scenes'][0],
    index: number,
    x: number,
    y: number,
    width: number,
    imageCache: Map<string, string>,
) {
    const boxHeight = PAGE_HEIGHT - MARGIN * 2;

    // 场景框
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.5);
    doc.roundedRect(x, y, width, boxHeight, 3, 3, 'S');

    // 场景编号 + 类型
    let headerY = y + 8;
    doc.setFontSize(10);
    doc.setTextColor(124, 58, 237);
    let headerText = `#${index + 1}`;
    if (scene.sceneType && SCENE_TYPE_LABELS[scene.sceneType]) {
        headerText += ` [${SCENE_TYPE_LABELS[scene.sceneType]}]`;
    }
    doc.text(headerText, x + 5, headerY);

    // 时长
    doc.setTextColor(120, 120, 120);
    doc.setFontSize(9);
    doc.text(`${scene.durationSec}s`, x + width - 5, headerY, { align: 'right' });

    // 分镜图
    let imageEndY = headerY + 5;
    const imgBase64 = imageCache.get(scene.id);
    if (imgBase64) {
        const imgWidth = width - 10;
        const imgHeight = Math.min(imgWidth * 0.5625, boxHeight * 0.45); // 16:9 比例，但不超过半高
        try {
            doc.addImage(imgBase64, 'JPEG', x + 5, imageEndY, imgWidth, imgHeight);
            imageEndY += imgHeight + 5;
        } catch {
            // 图片加载失败，跳过
            imageEndY += 5;
        }
    } else {
        // 占位框
        doc.setFillColor(245, 245, 245);
        doc.roundedRect(x + 5, imageEndY, width - 10, 40, 2, 2, 'F');
        doc.setFontSize(8);
        doc.setTextColor(180, 180, 180);
        doc.text('No image', x + width / 2, imageEndY + 22, { align: 'center' });
        imageEndY += 45;
    }

    // 旁白
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('Narration:', x + 5, imageEndY);
    imageEndY += 5;

    doc.setTextColor(60, 60, 60);
    doc.setFontSize(9);
    const narrationLines = doc.splitTextToSize(scene.narration || '(empty)', width - 10);
    doc.text(narrationLines.slice(0, 3), x + 5, imageEndY);
    imageEndY += Math.min(narrationLines.length, 3) * 4 + 5;

    // 画面描述
    if (imageEndY < y + boxHeight - 20) {
        doc.setFontSize(8);
        doc.setTextColor(100, 100, 100);
        doc.text('Visual:', x + 5, imageEndY);
        imageEndY += 5;

        doc.setTextColor(80, 80, 80);
        doc.setFontSize(8);
        const visualLines = doc.splitTextToSize(scene.visualPrompt || '(empty)', width - 10);
        doc.text(visualLines.slice(0, 3), x + 5, imageEndY);
    }
}
